language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

script:
  - cd ${TRAVIS_BUILD_DIR}/app/ && go build

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
    file: ${TRAVIS_BUILD_DIR}/app/app
